adalberto13/apps/participar/urls.py
from django.conf.urls.defaults import *
from adalberto13.apps.participar.views import ParticiparView

urlpatterns = patterns('',
    url(r'^$', ParticiparView.as_view(), name='participar'),
    (r'^sucesso/$', 'django.views.generic.simple.direct_to_template', {'template': 'sucesso.html'} ),
)

adalberto13/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'adalberto13.views.home', name='home'),
    url(r'^participar/', include('adalberto13.apps.participar.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adalberto13/apps/participar/models.py
# -*- coding: utf-8 -*-
from django.db import models

class Participar(models.Model):
    nome = models.CharField(max_length=255)
    email = models.EmailField("E-mail")
    endereco = models.CharField(max_length=255)
    bairro = models.CharField(max_length=15)
    telefone = models.CharField(max_length=15)
    voluntario = models.BooleanField()
    doacao = models.BooleanField()
    santinho = models.BooleanField()
    bandeira = models.BooleanField()
    adesivo = models.BooleanField()
    receber_email = models.BooleanField()

    def __unicode__(self):
        return '%s - %s' % (self.nome, self.email)

adalberto13/apps/participar/views.py
# -*- coding: utf-8 -*-
from django.views.generic.edit import CreateView
from adalberto13.apps.participar.models import Participar


class ParticiparView(CreateView):
    model = Participar
    template_name = 'base.html'
    success_url = '/participar/sucesso'

adalberto13/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'base.html', {})

adalberto13/templates/base.html
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta property="og:title" content="Adalberto Franklin 13 - Prefeito - Um novo caminho para Imperatriz">
  <meta property="og:description" content="Junte-se a nós na construção de um governo democrático, transparente, honesto e competente">
  <meta property="og:type" content="website">
  <meta property="og:url" content="http://adalberto13.com.br">
  <meta property="og:image" content="http://adalberto13.com.br{{ STATIC_URL }}img/icone_adalberto.jpg" />
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title></title>
  <meta name="description" content="">

  <meta name="viewport" content="width=device-width">
  <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css">

  <script src="{{ STATIC_URL }}js/libs/modernizr-2.5.3.min.js"></script>
</head>
<body>
  <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
  <div role="main" id="main">
    <h1 class="visuallyhidden">Adalberto 13 - vice: Professor Jorge</h1>
    <h2 class="visuallyhidden">Um novo caminho para Imperatriz</h2>
    <div class="frase">
      <h3>Participe da nossa campanha!</h3>
      <p>
        Junte-se a nós na construção de um governo democrático, transparente, honesto e competente.
      </p>
    </div>
    <a class="facebook" href="http://www.facebook.com/adalbertofranklin13" title="Curtir no facebook: Adalberto 13" target="_bank"></a>
    {% block box %}
    <form action="{% url participar %}" method="post">
      {% csrf_token %}
      <fieldset class="form1">
        <div class="field-sep">
          <input type="text" name="nome" placeholder="Nome:">
        </div>
        <div class="field-sep">
          <input type="email" name="email" placeholder="Seu email:">
        </div>
        <div class="field-sep">
          <input type="text" name="endereco" placeholder="Endereço:">
        </div>
        <div class="field-group">
          <div class="field-sep">
            <input type="text" name="bairro" placeholder="Bairro:">
          </div>
          <div class="field-sep">
            <input type="text" name="telefone" placeholder="Telefone:">
          </div>        
        </div>
        <div class="field-check">
          <input id="id_receive_mail" name="receber_email" type="checkbox" checked>
          <label for="id_receive_mail">Receber e-mails sobre a campanha</label>
        </div>
      </fieldset>
      <fieldset class="form2">
        <div class="field-check">
          <input id="id_voluntario" name="voluntario" type="checkbox">
          <label for="id_voluntario">Quero ser voluntário com o meu trabalho.</label>
        </div>
        <div class="field-check">
          <input id="id_doacao" name="doacao" type="checkbox">
          <label for="id_doacao">Quero fazer doação financeira.</label>
        </div>
        <div class="field-check">
          <input id="id_santinho" name="santinho" type="checkbox">
          <label for="id_santinho">Quero santinhos ou adesivos.</label>
        </div>
        <div class="field-check">
          <input id="id_bandeira" name="bandeira" type="checkbox">
          <label for="id_bandeira">Quero bandeiras para carro ou moto.</label>
        </div>
        <div class="field-check">
          <input id="id_adesivo" name="adesivo" type="checkbox">
          <label for="id_adesivo">Quero adesivo furado para carro.</label>
        </div>
      </fieldset>
      <input class="input-submit ir" type="submit">
    </form>
    {% endblock box %}
    <div class="vereadores-cycle">
      <div class="controls bt-prev"></div>
      <div class="cycle-in">
        {% for o in "123" %}
        <ul>
          {% for i in "1234" %}
          <li{% if forloop.last %} class="noborder"{% endif %}>
            <a href="#"><img src="{{ MEDIA_URL }}vereadores/{{ o }}{{ i }}.jpg" alt="#"></a>
            <h4>Candidado PT</h4>
          </li>
          {% endfor %}
        </ul>
        {% endfor %}
      </div>
      <div class="controls bt-next"></div>
    </div>
  </div>
  <footer class="rodape">
    <p>
      <b>www.adalberto13.com.br</b> - Campanha majoritária do Partido dos Trabalhadores / Imperatriz-MA
    </p>    
  </footer>

  <!--<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>-->
  <script>window.jQuery || document.write('<script src="{{ STATIC_URL }}js/libs/jquery-1.7.1.min.js"><\/script>')</script>
  <script src="{{ STATIC_URL }}js/jquery.cycle.all.js"></script>
  <script src="{{ STATIC_URL }}js/script.js"></script>

<!--  <script>
    var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
  </script>-->
</body>
</html>